const path = require('path');

async function generateReport(data) {
  const { architecture, security, dependencies, tests, quality, findings, fixes, generatedTests, repoPath } = data;

  const criticalFindings = findings.filter(f => f.severity === 'critical');
  const highFindings = findings.filter(f => f.severity === 'high');

  const securityScore = computeSecurityScore(findings);
  const qualityScore = computeQualityScore(findings);

  const markdown = generateMarkdown(data, securityScore, qualityScore);
  const json = generateJSON(data, securityScore, qualityScore);

  return {
    markdown,
    json,
    securityScore,
    qualityScore,
    generatedAt: new Date().toISOString(),
    summary: {
      repository: path.basename(repoPath),
      totalFindings: findings.length,
      critical: criticalFindings.length,
      high: highFindings.length,
      securityScore,
      qualityScore,
      testCoverage: tests.coverageEstimate,
      fixesGenerated: fixes.length,
      testsGenerated: generatedTests.length
    }
  };
}

function generateMarkdown(data, securityScore, qualityScore) {
  const { architecture, security, dependencies, tests, quality, findings, fixes, generatedTests, repoPath } = data;
  const now = new Date().toISOString();
  const repoName = path.basename(repoPath);

  const lines = [
    `# DevGuardian AI — Engineering Security Report`,
    ``,
    `**Repository:** \`${repoName}\`  `,
    `**Generated:** ${now}  `,
    `**Total Findings:** ${findings.length}  `,
    `**Security Score:** ${securityScore}/100  `,
    `**Quality Score:** ${qualityScore}/100  `,
    ``,
    `---`,
    ``,
    `## Executive Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Files Analyzed | ${architecture.metrics.totalFiles} |`,
    `| Estimated LOC | ${architecture.metrics.estimatedLinesOfCode.toLocaleString()} |`,
    `| Primary Language | ${architecture.projectInfo.primaryLanguage} |`,
    `| Frameworks | ${architecture.projectInfo.frameworks.join(', ') || 'None detected'} |`,
    `| Test Coverage | ~${tests.coverageEstimate}% |`,
    `| Security Score | ${securityScore}/100 |`,
    `| Quality Score | ${qualityScore}/100 |`,
    ``,
    `## Findings by Severity`,
    ``,
    `| Severity | Count |`,
    `|----------|-------|`,
    `| 🔴 Critical | ${findings.filter(f => f.severity === 'critical').length} |`,
    `| 🟠 High | ${findings.filter(f => f.severity === 'high').length} |`,
    `| 🟡 Medium | ${findings.filter(f => f.severity === 'medium').length} |`,
    `| 🟢 Low | ${findings.filter(f => f.severity === 'low').length} |`,
    ``,
    `## Critical & High Findings`,
    ``,
  ];

  const critical = findings.filter(f => ['critical', 'high'].includes(f.severity)).slice(0, 20);
  for (const f of critical) {
    lines.push(`### [${f.severity.toUpperCase()}] ${f.message}`);
    lines.push(`- **Rule:** ${f.ruleId}`);
    lines.push(`- **Category:** ${f.category}`);
    lines.push(`- **File:** \`${f.file}:${f.line}\``);
    lines.push(`- **Evidence:** \`${f.evidence}\``);
    if (f.remediation) lines.push(`- **Fix:** ${f.remediation}`);
    lines.push(``);
  }

  lines.push(`## Security Scan Results`);
  lines.push(``);
  lines.push(`- Total Security Findings: ${security.summary.total}`);
  lines.push(`- Critical: ${security.summary.bySeverity.critical}`);
  lines.push(`- High: ${security.summary.bySeverity.high}`);
  lines.push(`- Files Scanned: ${security.summary.filesScanned}`);
  lines.push(``);

  lines.push(`## Dependency Risk Analysis`);
  lines.push(``);
  lines.push(`- Total Dependencies: ${dependencies.totalDependencies}`);
  lines.push(`- Risky Dependencies: ${dependencies.summary.total}`);
  lines.push(``);

  lines.push(`## Test Coverage`);
  lines.push(``);
  lines.push(`- Estimated Coverage: ~${tests.coverageEstimate}%`);
  lines.push(`- Test Files: ${tests.testFiles}`);
  lines.push(`- Source Files: ${tests.sourceFiles}`);
  lines.push(`- Untested Files: ${tests.untestedFiles.length}`);
  lines.push(``);

  if (fixes.length > 0) {
    lines.push(`## Generated Fixes (${fixes.length})`);
    lines.push(``);
    for (const fix of fixes.slice(0, 10)) {
      lines.push(`### Fix for \`${fix.file}:${fix.line}\``);
      lines.push(`**Issue:** ${fix.issue}`);
      lines.push(`**Remediation:** ${fix.remediation}`);
      if (fix.codeExample) {
        lines.push(``);
        lines.push('```');
        lines.push(fix.codeExample);
        lines.push('```');
      }
      lines.push(``);
    }
  }

  if (generatedTests.length > 0) {
    lines.push(`## Generated Tests (${generatedTests.length})`);
    lines.push(``);
    for (const t of generatedTests) {
      lines.push(`- \`${t.file}\` (${t.framework})`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by DevGuardian AI*`);

  return lines.join('\n');
}

function generateJSON(data, securityScore, qualityScore) {
  return {
    meta: {
      tool: 'DevGuardian AI',
      version: '1.0.0',
      generatedAt: new Date().toISOString(),
      repository: path.basename(data.repoPath)
    },
    scores: { securityScore, qualityScore, testCoverage: data.tests.coverageEstimate },
    architecture: {
      primaryLanguage: data.architecture.projectInfo.primaryLanguage,
      languages: data.architecture.projectInfo.languages,
      frameworks: data.architecture.projectInfo.frameworks,
      metrics: data.architecture.metrics
    },
    findings: {
      total: data.findings.length,
      bySeverity: {
        critical: data.findings.filter(f => f.severity === 'critical').length,
        high: data.findings.filter(f => f.severity === 'high').length,
        medium: data.findings.filter(f => f.severity === 'medium').length,
        low: data.findings.filter(f => f.severity === 'low').length,
      },
      items: data.findings
    },
    fixes: data.fixes,
    generatedTests: data.generatedTests,
    security: data.security.summary,
    dependencies: { total: data.dependencies.totalDependencies, risks: data.dependencies.summary },
    tests: data.tests.summary
  };
}

function computeSecurityScore(findings) {
  const secFindings = findings.filter(f => f.source === 'security' || f.source === 'dependency');
  let deductions = 0;
  for (const f of secFindings) {
    if (f.severity === 'critical') deductions += 15;
    else if (f.severity === 'high') deductions += 8;
    else if (f.severity === 'medium') deductions += 3;
    else deductions += 1;
  }
  return Math.max(0, 100 - deductions);
}

function computeQualityScore(findings) {
  const qualFindings = findings.filter(f => f.source === 'quality');
  let deductions = 0;
  for (const f of qualFindings) {
    if (f.severity === 'high') deductions += 5;
    else if (f.severity === 'medium') deductions += 2;
    else deductions += 0.5;
  }
  return Math.max(0, 100 - Math.round(deductions));
}

module.exports = { generateReport };
