/**
 * Report Agent — generate Markdown + JSON reports
 */
function generateReport(results) {
  const { summary, security, quality, tests, dependencies, architecture, fixes, generatedTests } = results;

  const criticalCount = summary?.critical || 0;
  const highCount = summary?.high || 0;

  const securityScore = Math.max(0, 100 - (criticalCount * 20) - (highCount * 10) - ((summary?.medium || 0) * 3));
  const qualityScore = Math.max(0, 100 - (quality?.metrics?.totalIssues || 0) * 2);
  const testScore = tests?.summary?.estimatedCoverage || 0;
  const overallScore = Math.round((securityScore + qualityScore + testScore) / 3);

  const markdown = buildMarkdown(results, { securityScore, qualityScore, testScore, overallScore });
  const json = buildJson(results, { securityScore, qualityScore, testScore, overallScore });

  return { markdown, json, scores: { security: securityScore, quality: qualityScore, tests: testScore, overall: overallScore } };
}

function buildMarkdown(results, scores) {
  const { summary, security, quality, tests, dependencies, architecture, fixes, generatedTests } = results;
  const now = new Date().toISOString();
  const projectName = architecture?.projectInfo?.primaryLanguage || 'Project';

  const lines = [
    `# DevGuardian AI — Security & Quality Report`,
    `**Generated:** ${now}`,
    `**Project:** ${projectName} | **Language:** ${architecture?.projectInfo?.primaryLanguage || 'Unknown'}`,
    '',
    '## Executive Summary',
    '',
    `| Metric | Score |`,
    `|--------|-------|`,
    `| Overall Health | ${scores.overall}/100 |`,
    `| Security Score | ${scores.security}/100 |`,
    `| Code Quality | ${scores.quality}/100 |`,
    `| Test Coverage | ${scores.tests}% |`,
    '',
    '## Findings Overview',
    '',
    `| Severity | Count |`,
    `|----------|-------|`,
    `| 🔴 Critical | ${summary?.critical || 0} |`,
    `| 🟠 High | ${summary?.high || 0} |`,
    `| 🟡 Medium | ${summary?.medium || 0} |`,
    `| 🔵 Low | ${summary?.low || 0} |`,
    `| **Total** | **${summary?.total || 0}** |`,
    '',
    '## Security Findings',
    '',
  ];

  if (security?.findings?.length > 0) {
    for (const f of security.findings) {
      lines.push(`### ${f.severity.toUpperCase()}: ${f.title}`);
      lines.push(`- **Rule:** ${f.id} | **OWASP:** ${f.owasp}`);
      lines.push(`- **File:** \`${f.file}\` line ${f.line}`);
      lines.push(`- **Evidence:** \`${f.evidence}\``);
      lines.push(`- **Fix:** ${f.fix}`);
      lines.push('');
    }
  } else {
    lines.push('No security findings.\n');
  }

  lines.push('## Code Quality Findings', '');
  if (quality?.findings?.length > 0) {
    for (const f of quality.findings.slice(0, 20)) {
      lines.push(`- **[${f.severity.toUpperCase()}]** ${f.title} — \`${f.file}:${f.line}\``);
    }
  } else {
    lines.push('No quality findings.\n');
  }

  lines.push('', '## Dependency Risks', '');
  if (dependencies?.findings?.length > 0) {
    for (const f of dependencies.findings) {
      lines.push(`- **[${f.severity.toUpperCase()}]** ${f.evidence} — ${f.message} (${f.cve || ''})`);
    }
  } else {
    lines.push('No dependency vulnerabilities detected.\n');
  }

  lines.push('', '## Test Coverage', '');
  lines.push(`- Estimated coverage: **${tests?.summary?.estimatedCoverage || 0}%**`);
  lines.push(`- Test files: ${tests?.summary?.testFiles || 0}`);
  lines.push(`- Untested files: ${tests?.summary?.untestedFiles || 0}`);

  if (fixes?.length > 0) {
    lines.push('', '## Recommended Fixes', '');
    for (const fix of fixes.slice(0, 10)) {
      lines.push(`### ${fix.title}`);
      lines.push(`**File:** \`${fix.file}\` | **Effort:** ${fix.effort}`);
      lines.push(`> ${fix.suggestion}`);
      if (fix.codeAfter) {
        lines.push('```', fix.codeAfter, '```');
      }
      lines.push('');
    }
  }

  lines.push('---', '*Report generated by DevGuardian AI*');
  return lines.join('\n');
}

function buildJson(results, scores) {
  return {
    metadata: {
      generatedAt: new Date().toISOString(),
      version: '1.0.0',
      platform: 'DevGuardian AI',
    },
    scores,
    summary: results.summary,
    security: { findings: results.security?.findings || [], categories: groupByCategory(results.security?.findings || []) },
    quality: { findings: results.quality?.findings || [], metrics: results.quality?.metrics || {} },
    tests: results.tests || {},
    dependencies: results.dependencies || {},
    architecture: results.architecture || {},
    fixes: results.fixes || [],
    generatedTests: results.generatedTests || [],
  };
}

function groupByCategory(findings) {
  const categories = {};
  for (const f of findings) {
    if (!categories[f.owasp]) categories[f.owasp] = [];
    categories[f.owasp].push(f);
  }
  return categories;
}

module.exports = { generateReport };
