/**
 * Test Agent — generate regression tests for code files
 */
const path = require('path');
const { readFileSafe } = require('../utils/fileUtils');
const { generateText } = require('../ai/aiProvider');

async function generateTests(files, findings) {
  const generatedTests = [];
  const codeExts = new Set(['.js', '.jsx', '.ts', '.tsx', '.py', '.go']);
  const testPatterns = [/\.test\.|\.spec\.|__tests__/, /\/tests?\//, /\/spec\//];

  // Group findings by file
  const findingsByFile = {};
  for (const f of findings) {
    if (!findingsByFile[f.file]) findingsByFile[f.file] = [];
    findingsByFile[f.file].push(f);
  }

  const targetFiles = files.filter(f =>
    codeExts.has(f.ext) &&
    !testPatterns.some(p => p.test(f.relativePath)) &&
    (findingsByFile[f.relativePath] || f.size < 20000)
  ).slice(0, 10); // Limit to 10 files

  for (const file of targetFiles) {
    const content = readFileSafe(file.path);
    if (!content) continue;

    const fileFindings = findingsByFile[file.relativePath] || [];
    const testCode = await buildTestCode(file, content, fileFindings);

    const testFileName = buildTestFileName(file);
    generatedTests.push({
      file: file.relativePath,
      testFile: testFileName,
      language: file.language,
      code: testCode,
      findingsCovered: fileFindings.map(f => f.id),
    });
  }

  return generatedTests;
}

async function buildTestCode(file, content, findings) {
  // Try AI generation first
  if (process.env.AI_PROVIDER && process.env.AI_PROVIDER !== 'none') {
    try {
      const prompt = [
        `Generate Jest unit tests for this ${file.language} file: ${file.relativePath}`,
        `Focus on these issues: ${findings.map(f => f.title).join(', ') || 'general coverage'}`,
        'Write 3-5 test cases. Use describe/it/expect. Do not import the actual file, just show the test structure.',
        '--- CODE SNIPPET ---',
        content.slice(0, 1000),
      ].join('\n');
      const aiCode = await generateText(prompt, { maxTokens: 600 });
      if (aiCode) return aiCode;
    } catch { /* use rule-based */ }
  }

  return buildRuleBasedTest(file, content, findings);
}

function buildRuleBasedTest(file, content, findings) {
  const moduleName = path.basename(file.relativePath, file.ext);
  const importPath = './' + moduleName;

  // Extract exported function names
  const exportedFunctions = [];
  const exportRe = /(?:module\.exports\s*=\s*\{([^}]+)\}|export\s+(?:default\s+)?(?:function|const|class)\s+(\w+))/g;
  let m;
  while ((m = exportRe.exec(content)) !== null) {
    if (m[1]) exportedFunctions.push(...m[1].split(',').map(s => s.trim()).filter(Boolean));
    if (m[2]) exportedFunctions.push(m[2]);
  }

  const lines = [
    "/**",
    ` * Auto-generated regression tests for ${file.relativePath}`,
    ` * Generated by DevGuardian AI Test Agent`,
    " */",
    "",
  ];

  if (file.ext === '.py') {
    lines.push(`import pytest`);
    lines.push(`# from ${moduleName} import *`);
    lines.push('');
    lines.push(`class Test${toPascalCase(moduleName)}:`);
    for (const fn of exportedFunctions.slice(0, 3)) {
      lines.push(`    def test_${fn}_basic(self):`);
      lines.push(`        # TODO: implement`);
      lines.push(`        assert True`);
      lines.push('');
    }
    for (const finding of findings.slice(0, 2)) {
      lines.push(`    def test_security_${finding.id.toLowerCase().replace('-', '_')}(self):`);
      lines.push(`        """Test: ${finding.title}"""`);
      lines.push(`        # ${finding.fix}`);
      lines.push(`        assert True  # Replace with real assertion`);
      lines.push('');
    }
  } else {
    lines.push(`const { ${exportedFunctions.slice(0, 3).join(', ') || 'main'} } = require('${importPath}');`);
    lines.push('');
    lines.push(`describe('${moduleName}', () => {`);

    if (exportedFunctions.length > 0) {
      for (const fn of exportedFunctions.slice(0, 3)) {
        lines.push(`  describe('${fn}', () => {`);
        lines.push(`    it('should exist and be callable', () => {`);
        lines.push(`      expect(typeof ${fn}).toBe('function');`);
        lines.push(`    });`);
        lines.push('');
        lines.push(`    it('should handle valid input', () => {`);
        lines.push(`      // TODO: test with valid input`);
        lines.push(`      expect(true).toBe(true);`);
        lines.push(`    });`);
        lines.push('');
        lines.push(`    it('should handle invalid input gracefully', () => {`);
        lines.push(`      // TODO: test error cases`);
        lines.push(`      expect(() => ${fn}(null)).not.toThrow();`);
        lines.push(`    });`);
        lines.push(`  });`);
        lines.push('');
      }
    }

    for (const finding of findings.slice(0, 3)) {
      lines.push(`  it('security: ${finding.title.toLowerCase().replace(/[^a-z0-9 ]/g, '')}', () => {`);
      lines.push(`    // Finding: ${finding.id} at ${finding.file}:${finding.line}`);
      lines.push(`    // ${finding.fix}`);
      lines.push(`    expect(true).toBe(true); // Replace with real security assertion`);
      lines.push(`  });`);
      lines.push('');
    }

    lines.push(`});`);
  }

  return lines.join('\n');
}

function buildTestFileName(file) {
  const dir = path.dirname(file.relativePath);
  const base = path.basename(file.relativePath, file.ext);
  if (file.ext === '.py') return path.join(dir, `test_${base}.py`);
  return path.join(dir, `${base}.test${file.ext}`);
}

function toPascalCase(str) {
  return str.replace(/[-_](\w)/g, (_, c) => c.toUpperCase()).replace(/^\w/, c => c.toUpperCase());
}

module.exports = { generateTests };
